# Using the node alpine image to build the React app
image: node:buster

# Announce the URL as per CRA docs
# https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#advanced-configuration
variables:
  PUBLIC_URL: /
# Cache node modules - speeds up future builds


# Name the stages involved in the pipeline
stages:
-  test
-  build
-  deploy

#cache:
#  paths:
#    - node_modules/
#    - Api/node_modules/
 #   - frontend/node_modules/
# Job name for gitlab to recognise this results in assets for Gitlab Pages
# https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-requirements
testapi:
  stage: test
  services:
    - mongo:latest
  script:
    - cd Api
    - npm i npm@latest -g
    - npm i
    - npm test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'
buildapi:
  image:  
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  
  script:
    - cd Api
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/Api --dockerfile $CI_PROJECT_DIR/Api/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
#    - docker run my-docker-image /script/to/run/tests

pagesbuild:
    stage: build
    script:
      - cd frontend
      - echo "Building deploy package"
      - yarn install
      - yarn build
      - echo "Build successful"
    artifacts:
      paths:
        - frontend/build
pages:
  stage: deploy
  dependencies:
    - pagesbuild
  script:
    - ls
    - cd frontend
    - ls
    - cp public/index.html public/404.html # Not necessary, but helps with https://medium.com/@pshrmn/demystifying-single-page-applications-3068d0555d46
    - mv public _public # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build ../public # Move build files to public dir for Gitlab Pages
  artifacts:
    paths:
    - public # The built files for Gitlab Pages to serve
  only:
    - master # Only run on master branch